##########################################
# 				Solr 5.2
##########################################

# base image.
FROM rajsaxena/java8

# File Author / Maintainer
MAINTAINER Raj <rajs@mangospring.com>

LABEL Description="A layer of Solr server on top of Java container"

COPY solr_5.2.0 /solr_5.2
# ENTRYPOINT ["/solr_5.2/bin/solr"]

#Exposing Solr port 
EXPOSE 8989
